using System;
using System.Collections.Generic;
using System.Text;

namespace DatabaseLibrary.Models
{
    public class Client_db
    {

        #region Constructors

        /// <summary>
        /// Default Constructor
        /// </summary>
        public Client_db()
        {

        }
        /// <summary>
        /// Fields constructor.
        /// </summary>
        public Client_db(string id, string firstName, string lastName, double weight, double height, double cv, double bfp)
        {
            Id = id;
            FirstName = firstName;
            LastName = lastName;
            Weight = weight;
            Height = height;
            CV = cv;
            BFP = bfp;
        }

        #endregion

        #region Prperties

        /// <summary>
        /// Id generated by our system upon creation of a new instance.
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// First name used of the student.
        /// </summary>
        public string FirstName { get; set; }

        /// <summary>
        /// Last name used of the student.
        /// </summary>
        public string LastName { get; set; }

        /// <summary>
        /// Last name used of the student.
        /// </summary>
        public double Weight { get; set; }

        /// <summary>
        /// Last name used of the student.
        /// </summary>
        public double Height { get; set; }

        /// <summary>
        /// Last name used of the student.
        /// </summary>
        public double CV { get; set; }

        /// <summary>
        /// Last name used of the student.
        /// </summary>
        public double BFP { get; set; }

        #endregion

    }
}
