using System;
using System.Collections.Generic;
using System.Text;

namespace DatabaseLibrary.Models
{
    public class Client_db
    {

        #region Constructors

        /// <summary>
        /// Default constructor.
        /// </summary>
        public Client_db()
        {
        }

        /// <summary>
        /// Fields constructor.
        /// </summary>
        public Client_db(int id, string firstName, string lastName, double weight, double height, double waistCircumference, double hipCircumference, double neckCircumference)
        {
            Id = id;
            FirstName = firstName;
            LastName = lastName;
            Weight = weight;
            Height = height;
            WaistCircumference = waistCircumference;
            HipCircumference = hipCircumference;
            NeckCircumference = neckCircumference;
        }

        #endregion

        #region Properties

        /// <summary>
        /// Id generated by our system upon creation of a new instance.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// First name used of the client.
        /// </summary>
        public string FirstName { get; set; }

        /// <summary>
        /// Last name used of the client.
        /// </summary>
        public string LastName { get; set; }

        /// <summary>
        /// Weight of the client.
        /// </summary>
        public double Weight { get; set; }

        /// <summary>
        /// Height of the client.
        /// </summary>
        public double Height { get; set; }

        /// <summary>
        /// Waist Circumference of the client.
        /// </summary>
        public double WaistCircumference { get; set; }

        /// <summary>
        /// Hip Circumference of the client.
        /// </summary>
        public double HipCircumference { get; set; }

        /// <summary>
        /// Neck Circumference of the client.
        /// </summary>
        public double NeckCircumference { get; set; }

        #endregion

    }
}
