using System;
using System.Collections.Generic;
using System.Text;

namespace DatabaseLibrary.Models
{
    public class Client_db
    {

        #region Constructors

        /// <summary>
        /// Default constructor.
        /// </summary>
        public Client_db()
        {
        }

        /// <summary>
        /// Fields constructor.
        /// </summary>
        public Client_db(int id, string firstName, string lastName, double weight, double height, double cv, double bfp)
        {
            Id = id;
            FirstName = firstName;
            LastName = lastName;
            Weight = weight;
            Height = height;
            Cv = cv;
            Bfp = bfp;
        }

        #endregion

        #region Properties

        /// <summary>
        /// Id generated by our system upon creation of a new instance.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// First name used of the student.
        /// </summary>
        public string FirstName { get; set; }

        /// <summary>
        /// Last name used of the student.
        /// </summary>
        public string LastName { get; set; }

        public double Weight { get; set; }

        public double Height { get; set; }

        public double Cv { get; set; }

        public double Bfp { get; set; }

        #endregion

    }
}
