using System;
using System.Collections.Generic;
using System.Text;

namespace DatabaseLibrary.Models
{
    public class Dietician_db
    {

        #region Constructors

        /// <summary>
        /// Default constructor.
        /// </summary>
        public Dietician_db()
        {
        }

        /// <summary>
        /// Fields constructor.
        /// </summary>
        public Dietician_db(int id, DateTime dob, string name, string practice, string doctorate, string bachelorsDegree, string associatesDegree, string certification)
        {
            Id = id;
            Dob = dob;
            Name = name;
            Practice = practice;
            Doctorate = doctorate;
            BachelorsDegree = bachelorsDegree;
            AssociatesDegree = associatesDegree;
            Certification = certification;
        }

        #endregion

        #region Properties

        /// <summary>
        /// Id generated by our system upon creation of a new instance.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// date of birth
        /// </summary>

        public DateTime Dob { get; set; }

        /// <summary>
        /// Name used of the dietician.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// practice of the dietician
        /// </summary>
        public string Practice { get; set; }

        /// <summary>
        /// doctorate of the dietician
        /// </summary>
        public string Doctorate { get; set; }

        /// <summary>
        /// bachelors of the dietician
        /// </summary>
        public string BachelorsDegree { get; set; }

        /// <summary>
        /// associates of the dietician
        /// </summary>
        public string AssociatesDegree { get; set; }

        /// <summary>
        /// certification of the dietician
        /// </summary>
        public string Certification { get; set; }

        #endregion

    }
}
