using System;
using System.Collections.Generic;
using System.Text;

namespace DatabaseLibrary.Models
{
    public class ExerciseSet_db
    {

        #region Contructors

        /// <summary>
        /// Default constructor. 
        /// Default constructor. 
        /// Need for serialization purposes.
        /// </summary>
        public ExerciseSet_db()
        {
        }

        /// <summary>
        /// Fields constructor.
        /// </summary>
        public ExerciseSet_db(int id, DateTime date, TimeSpan time, int weight, string type, int reps, int setNumber)
        {
            Id = id;
            Date = date;
            Time = time;
            Weight = weight;
            Type = type;
            Reps = reps;
            SetNumber = setNumber;

        }

        #endregion

        #region Properties

        /// <summary>
        /// Id generated by our system upon creation of a new instance.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// First name of the client.
        /// </summary>
        public DateTime Date { get; set; }

        /// <summary>
        /// Last name of the client.
        /// </summary>
        public TimeSpan Time { get; set; }

        /// <summary>
        /// Instructor's training type
        /// </summary>
        public int Weight { get; set; }

        public string Type { get; set; }

        public int Reps { get; set; }

        public int SetNumber { get; set; }

        #endregion
    }
}