using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Text;

namespace BusinessLibrary.Models
{
	class ExerciseSet
    {
        #region Contructors

        /// <summary>
        /// Default constructor. 
        /// Need for serialization purposes.
        /// </summary>
        public ExerciseSet()
        {
        }

        /// <summary>
        /// Fields constructor.
        /// </summary>
        public ExerciseSet(int id, DateTime date, TimeSpan time, int caloriesBurned, string type, int reps, int setNumber)
        {
            Id = id;
            Date = date;
            Time = time;
            CaloriesBurned = caloriesBurned;
            Type = type;
            Reps = reps;
            SetNumber = setNumber;

        }

        /// <summary>
        /// Clone/Copy constructor.
        /// </summary>
        /// <param name="instance">The object to clone from.</param>
        public ExerciseSet(ExerciseSet instance)
            : this(instance.Id, instance.Date, instance.Time, instance.CaloriesBurned, instance.Type, instance.Reps, instance.SetNumber)
        {
        }

        #endregion

        #region Properties

        /// <summary>
        /// Id generated by our system upon creation of a new instance.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int Id { get; set; }

        /// <summary>
        /// First name of the client.
        /// </summary>
        [JsonProperty(PropertyName = "date")]
        public DateTime Date { get; set; }

        /// <summary>
        /// Last name of the client.
        /// </summary>
        [JsonProperty(PropertyName = "time")]
        public TimeSpan Time { get; set; }

        /// <summary>
        /// Instructor's training type
        /// </summary>
        [JsonProperty(PropertyName = "caloriesBurned")]
        public int CaloriesBurned { get; set; }

        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        [JsonProperty(PropertyName = "reps")]
        public int Reps { get; set; }

        [JsonProperty(PropertyName = "setNumber")]
        public int SetNumber { get; set; }

        #endregion
    }
}