using Nest;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Text;

namespace BusinessLibrary.Models
{
	public class FitnessProgram
	{
		#region Constructors

		/// <summary>
		/// Default constructor. 
		/// Need for serialization purposes.
		/// </summary>
		public FitnessProgram()
		{
		}

		/// <summary>
		/// Fields constructor.
		/// </summary>
		public FitnessProgram(int id, string name, string description, string routine, DateTime creationDate, string video, string type, string modality)
        {
			Id = id;
			Name = name;
			Description = description;
			Routine = routine;
			CreationDate = creationDate;
			Video = video;
			Type = type;
			Modality = modality;
        }

		#endregion

		#region Properties

		/// <summary>
		/// Id generated by our system upon creation of a new instance.
		/// </summary>
		[JsonProperty(PropertyName = "id")]
		public int Id { get; set; }

		[JsonProperty(PropertyName = "name")]
		public string Name { get; set; }

		[JsonProperty(PropertyName = "description")]
		public string Description { get; set; }

		[JsonProperty(PropertyName = "routine")]
		public string Routine { get; set; }

		[JsonProperty(PropertyName = "creationDate")]
		public DateTime CreationDate { get; set; }

		[JsonProperty(PropertyName = "video")]
		public string Video { get; set; }

		[JsonProperty(PropertyName = "type")]
		public string Type { get; set; }

		[JsonProperty(PropertyName = "modality")]
		public string Modality { get; set; }
		#endregion

		#region Methods

		#endregion
	}
}