using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Text;

namespace BusinessLibrary.Models
{
    public class SleepLog
    {
        #region Contructors

        /// <summary>
        /// Default constructor. 
        /// Need for serialization purposes.
        /// </summary>
        public SleepLog()
        {
        }

        /// <summary>
        /// Fields constructor.
        /// </summary>
        public SleepLog(int id, DateTime date, TimeSpan time, TimeSpan sleepDuration)
        {
            Id = id;
            Date = date;
            Time = time;
            SleepDuration = sleepDuration;
        }

        /// <summary>
        /// Clone/Copy constructor.
        /// </summary>
        /// <param name="instance">The object to clone from.</param>
        public SleepLog(SleepLog instance)
            : this(instance.Id, instance.Date, instance.Time, instance.SleepDuration)
        {
        }

        #endregion

        #region Properties

        /// <summary>
        /// Id generated by our system upon creation of a new instance.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int Id { get; set; }

        /// <summary>
        /// First name of the client.
        /// </summary>
        [JsonProperty(PropertyName = "date")]
        public DateTime Date { get; set; }

        /// <summary>
        /// Last name of the client.
        /// </summary>
        [JsonProperty(PropertyName = "time")]
        public TimeSpan Time { get; set; }

        /// <summary>
        /// Instructor's training type
        /// </summary>
        [JsonProperty(PropertyName = "sleepDuration")]
        public TimeSpan SleepDuration { get; set; }

        #endregion
    }
}
